apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  namespace: fractal
  labels:
    app: postgres
    project: fractal
data:
  POSTGRES_DB: fractal_api_db
  POSTGRES_USER: fractal_api
  POSTGRES_PASSWORD: root
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: fractal
  labels:
    type: local
    project: fractal
    app: postgres
spec:
  storageClassName: local-path
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  namespace: fractal
  labels:
    app: postgres
    project: fractal
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: fractal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        project: fractal
    spec:
      containers:
        - name: postgres
          image: postgis/postgis:16-3.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim
