apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage-rwm
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-fractal-data
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/fractal
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage-rwm
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-shared-api-core
  namespace: fractal
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-fractal-data
  storageClassName: local-storage-rwm
