apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-fractal-core
  namespace: fractal
data:
  DATABASE_DBNAME: "fractal_api_db"
  DATABASE_HOST: "postgres"
  DATABASE_PASSWORD: "root"
  DATABASE_PORT: "5432"
  DATABASE_USER: "fractal_api"
  FILEPATH_INPUT: /fractal/data/input
  FILEPATH_OUTPUT: /fractal/data/output
  PYTHONUNBUFFERED: "TRUE"
  IMAGE_VERSION: "dev"
  TZ: "America/Sao_Paulo"
  ACTIVEMQ_BROKER-URL: "active-mq"
  ACTIVEMQ_USER: "admin"
  ACTIVEMQ_PASSWORD: "admin"
  ACTIVEMQ_PORT: "61613"
  ACTIVEMQ_PROCESS-QUEUE: "fractal.start.process.queue"
  OSRM_URL: "http://192.168.129.129:5001"
  OSRM_SERVICE: "route"
  OSRM_VERSION: "v1"
  OSRM_PROFILE: "fiber"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fractal-core
  namespace: fractal
  labels:
    app: fractal-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fractal-core
  template:
    metadata:
      labels:
        app: fractal-core
    spec:
      containers:
      - name: fractal-core
        image: localhost:5000/fractal-core:3.8.7.0
        resources:
            requests:
              memory: "600M"
              cpu: "100m"
            limits:
              memory: "3500Mi"
              cpu: "2"
        ports:
        - containerPort: 5000
        envFrom:
          - configMapRef:
              name: configmap-fractal-core
        volumeMounts:
          - mountPath: /fractal/data
            name: fractal-data
      volumes:
        - name: fractal-data
          persistentVolumeClaim:
            claimName: pvc-shared-api-core
