apiVersion: apps/v1
kind: Deployment
metadata:
  name: fractal-webui
  namespace: fractal
  labels:
    app: fractal-mfe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fractal-mfe
  template:
    metadata:
      name: fractal-mfe
      labels:
        app: fractal-mfe
    spec:
      containers:
        - name: fractal-mfe
          image: registry.cezaodabahia.com.br/fractal-webui:3.9.6.5
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256M"
              cpu: "50m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: fractal-mfe
  namespace: fractal
spec:
  selector:
    app: fractal-mfe
  ports:
    - name: http
      nodePort: 31000
      port: 80
      protocol: TCP
      targetPort: 80
  type: NodePort

