apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudbeaver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudbeaver
  template:
    metadata:
      labels:
        app: cloudbeaver
    spec:
      containers:
        - name: cloudbeaver
          image: dbeaver/cloudbeaver:25
          ports:
            - containerPort: 8978
          volumeMounts:
            - name: workspace-volume
              mountPath: /opt/cloudbeaver/workspace
      volumes:
        - name: workspace-volume
          hostPath:
            path: /var/cloudbeaver/workspace
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: cloudbeaver-service
spec:
  type: NodePort
  selector:
    app: cloudbeaver
  ports:
    - port: 8978
      targetPort: 8978
      nodePort: 30978
